# Generated by Django 5.0.1 on 2024-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
